server:
  port: 9201
spring:
  application:
    name: spring-cloud-provider
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/