spring:
  application:
    name: eureka-gateway
server:
  port: 9991
zuul:
  routes:
    hello:
      path: /provider/**
      serviceId: spring-cloud-provider
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
management:
  security:
    enables: true
  server:
    port: 9992
    address: localhost
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: env,beans